In [ ]:
import numpy as np

C0=np.array([0.24,0.33,0.63])

C1=np.array([0.31,0.6,0.47])

C2=np.array([0.57,0.95,0.15])

E0 =np.array([1,	1,	1])
E1 =np.array([0,	1,	1])
E2 =np.array([1,	1,	0])
E3 =np.array([1,	0,	0])
E4 =np.array([0,	0,	1])
E5 =np.array([1,	0,	1])


In [ ]:
def f(C):
  v0 = sum(abs(C - C0))
  print(abs(C - C0))
  v1 = sum(abs(C - C1))
  print(abs(C - C1))
  v2 = sum(abs(C - C2))
  print(abs(C - C2))

  print(v0,v1,v2)

  if (v0 == v1 or v0 == v2 or v1 == v2):
    print("raios")

  if (v0<v1 and v0<v2):
    print("0")
  if (v1<v0 and v1<v2):
    print("1")
  if (v2<v0 and v2<v1):
    print("2")

In [ ]:
f(E0)

[0.76 0.67 0.37]
[0.69 0.4  0.53]
[0.43 0.05 0.85]
1.7999999999999998 1.6199999999999999 1.33
2


In [ ]:
f(E1)

1.2799999999999998 1.24 1.47
1


In [ ]:
f(E2)

2.06 1.5599999999999998 0.6300000000000001
2


In [ ]:
f(E3)

[0.76 0.33 0.63]
[0.69 0.6  0.47]
[0.43 0.95 0.15]
1.7200000000000002 1.76 1.5299999999999998
2


In [ ]:
f(E4)

0


In [ ]:
f(E5)

0


In [ ]:
s = E2 +E3 
s/2

array([1. , 0.5, 0. ])

In [ ]:
s1 = E1
s1

array([0, 1, 1])

In [ ]:
x = E4 + E5
x

array([1, 0, 2])

In [ ]:
x/2

array([0.5, 0. , 1. ])

#**Solucion**

**Entrada**

In [246]:
import numpy as np

Centroidesxyz = np.array([ [0.24,0.33,0.63],
                        [0.31,0.6,0.47] ,
                        [0.57,0.95,0.15]   ])

Datosxyz = np.array([[1,	1,	1],
                  [0,	1,	1],
                  [1,	1,	0],
                  [1,	0,	0],
                  [0,	0,	1],
                  [1,	0,	1]])


#-----------------------------------------

Datos = np.array([[0,	1,	1],
                  [1,	0,	0],
                  [0,	0,	1],
                  [1,	0,	1],
                  [0,	1,	0],
                  [0,	0,	0]])

Centroides = np.array([[0.52, 0.94, 0.88],
                       [0.33, 0.69, 0.81],
                       [0.29, 0.55, 0.8 ]])

**funciones utiles**

In [247]:
from numpy import linalg as LA
#ejemplo_norma = np.array([5,3])
ejemplo_norma = np.array([-0.69 -0.4  -0.53])
print(LA.norm(ejemplo_norma))
#print(np.sqrt(5**2 + 3**2))

1.6199999999999999


In [248]:
np.argmin([np.array([3,7,4,1,1,1,1])])

3

**Funciones determinar el cluster de cada dato**

In [249]:
def determinar_centroide(punto, centroides):
  numero_centroides = len(centroides)
  print("Centroides: ", numero_centroides)
  lista_distancias_del_cluster_a_cada_centroide = np.zeros(numero_centroides)
  print("inicializacion distancias: ",lista_distancias_del_cluster_a_cada_centroide)

  for i in range (0,numero_centroides):
    vector_diferencia = centroides[i] - punto
    distancia_i = LA.norm(vector_diferencia)
    lista_distancias_del_cluster_a_cada_centroide[i] = LA.norm(vector_diferencia)
    print("centroide: ", centroides[i],"| punto: ", punto,"| diferencia: ", vector_diferencia, "| distancia: ",lista_distancias_del_cluster_a_cada_centroide[i])
    
  print("distancias a cada centroide: ", lista_distancias_del_cluster_a_cada_centroide)

  cluster_a_ser_asignado = np.argmin(lista_distancias_del_cluster_a_cada_centroide)

  return cluster_a_ser_asignado

In [251]:
def determinar_centroides(datos, centroides):

  numero_centroides = len(centroides)
  numero_datos = len(datos)
  dimensiones = len(datos[0])

  datos_de_los_clusters = np.zeros((numero_centroides,dimensiones))
  conteo_datos_de_los_clusters = np.zeros(numero_centroides)

  n = 0
  for i in range(0,numero_datos):
    print("_________________________________________________________________\n",'\n[',i,']\n')
    cluster_del_dato_i = determinar_centroide(datos[i],centroides)
    anterior = datos_de_los_clusters[cluster_del_dato_i]
    actualizado = anterior + np.array(datos[i])
    print("anterior: ",anterior," nuevos: ", datos[i], " actualizado: ",actualizado)
    datos_de_los_clusters[cluster_del_dato_i] = actualizado

    conteo_datos_de_los_clusters[cluster_del_dato_i] += 1.0

    print( "\n< ", cluster_del_dato_i, " > \n")

  print("-------------------------\nAcumulados\n-------------------------\n")

  
  print(datos_de_los_clusters)
  print("\nConteo: ",conteo_datos_de_los_clusters)
  print("\n\n\nNuevos centroides\n ")

  for i in range(0,numero_centroides):
    print("calculo: ",datos_de_los_clusters[i],"/", conteo_datos_de_los_clusters[i])
    datos_de_los_clusters[i] = datos_de_los_clusters[i] / conteo_datos_de_los_clusters[i]

  print("\n\n",datos_de_los_clusters)
    

In [252]:
determinar_centroides(Datos, Centroides)

_________________________________________________________________
 
[ 0 ]

Centroides:  3
inicializacion distancias:  [0. 0. 0.]
centroide:  [0.52 0.94 0.88] | punto:  [0 1 1] | diferencia:  [ 0.52 -0.06 -0.12] | distancia:  0.5370288632839021
centroide:  [0.33 0.69 0.81] | punto:  [0 1 1] | diferencia:  [ 0.33 -0.31 -0.19] | distancia:  0.49101934788763674
centroide:  [0.29 0.55 0.8 ] | punto:  [0 1 1] | diferencia:  [ 0.29 -0.45 -0.2 ] | distancia:  0.5714892824891818
distancias a cada centroide:  [0.53702886 0.49101935 0.57148928]
anterior:  [0. 0. 0.]  nuevos:  [0 1 1]  actualizado:  [0. 1. 1.]

<  1  > 

_________________________________________________________________
 
[ 1 ]

Centroides:  3
inicializacion distancias:  [0. 0. 0.]
centroide:  [0.52 0.94 0.88] | punto:  [1 0 0] | diferencia:  [-0.48  0.94  0.88] | distancia:  1.3741906709041507
centroide:  [0.33 0.69 0.81] | punto:  [1 0 0] | diferencia:  [-0.67  0.69  0.81] | distancia:  1.257417989373462
centroide:  [0.29 0.55 0.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in true_divide


In [242]:
determinar_centroide(punto = Datos[3], centroides = Centroides)

Centroides:  3
inicializacion distancias:  [0. 0. 0.]
centroide:  [0.24 0.33 0.63] | punto:  [1 0 0] | diferencia:  [-0.76  0.33  0.63] | distancia:  1.0408650248711404
centroide:  [0.31 0.6  0.47] | punto:  [1 0 0] | diferencia:  [-0.69  0.6   0.47] | distancia:  1.02810505299799
centroide:  [0.57 0.95 0.15] | punto:  [1 0 0] | diferencia:  [-0.43  0.95  0.15] | distancia:  1.0535179163165664
distancias a cada centroide:  [1.04086502 1.02810505 1.05351792]


1